sprint 9
mybogdan/java-filmorate pull request #1
Opened 2023-07-11 20:36 UTC by mybogdan

2023-07-13 14:59 UTC, Yang-Pi requested changes
В ТЗ есть такой пункт "Добавьте тесты для валидации. Убедитесь, что она работает на граничных условиях.". Напиши пару тестов

2023-07-13 14:59 UTC, Yang-Pi commented on .gitignore
> +mvnw
Верно понимаю, что без этих изменений не получается пройти тесты? Потому что по идее вот этот файл и остальные, относящиеся с CI программы, не нужно менять и удалять.

2023-07-13 14:59 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
@NotBlank включает в себя проверку на null, поэтому можешь оставить только одну аннотацию.

2023-07-13 14:59 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/validation/ReleaseDate.java
> +public @interface ReleaseDate {
Здорово, что ты написал свою аннотацию, но почему-то нигде ее не используешь.

2023-07-13 20:37 UTC, mybogdan commented on .gitignore
> +mvnw
Ошибка "пул реквест содержит двоичные файлы. Удалите их"
Без них проходит

2023-07-14 11:14 UTC, Yang-Pi approved these changes

2023-07-14 11:14 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/validation/ReleaseDate.java
> +public @interface ReleaseDate {
Да зря ты удалил, просто использовал бы совместно с @Past

2023-07-25 06:51 UTC, merged