Add database
mybogdan/java-filmorate pull request #3
Opened 2023-10-08 15:42 UTC by mybogdan

2023-10-08 18:57 UTC, Yang-Pi commented
Вижу, что два этапа CI не в статусе success 🟢 , это нужно исправить

2023-10-08 19:12 UTC, mybogdan commented
> Вижу, что два этапа CI не в статусе success 🟢 , это нужно исправить

Сделано )

2023-10-08 19:15 UTC, Yang-Pi requested changes

2023-10-08 19:15 UTC, Yang-Pi commented on .gitignore
> +!.mvn/wrapper/maven-wrapper.jar
Ты зря изменил .gitignore файл, теперь ненужные файлы могут попасть в репозиторий. Была ли причина для этих изменений?

2023-10-08 19:15 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Одна строчка лишняя, а вообще если интересно насчет последней строки в файле, то https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file/18789#18789

2023-10-08 19:15 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
В рамках этой итерации проекта InMemory-реализации должны уже быть исключены

2023-10-08 19:15 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(genreDbStorage.getGenreForCurrentFilm(film.getId()));
⚠️ **Issue:** При текущей реализации количество запросов к бд равно кол-ву итераций цикла, что очень много. С точки зрения эффективности - нужно сделать один запрос, который получает и фильмы, и жанры, и лайки, и затем программно собрать коллекцию билдером.

2023-10-09 17:30 UTC, Yang-Pi approved these changes

2023-10-09 17:30 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film mapRowToFilm(ResultSet resultSet, int rowNum) throws SQLException {
Вот так лучше!

2023-10-09 17:49 UTC, merged